version: '3.8'

services:
  app:
    image: nginx:alpine
    container_name: gatepin
    ports:
      - "2024:80"  # Map host port 2024 to container port 80
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
